### ISSUE TITLE
你好 我想问下discriminative classification techniques 要如何翻译？

### ISSUE THREAD

**Issue by bringtree** [jiqizhixin/AI-Terminology-page#1]
来源http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.722.9492&rep=rep1&type=pdf
4背景中 出现了这个词汇  discriminative classification techniques 要怎么翻译好？
原句`With advances in machine learning over the last decade, especially in discriminative classification techniques, researchers have framed the ID problem as a sample classification task and SF as a sequence classification task.`

**Comment by HoratioJSY** [comment]
判别式分类技术，应该指的是属于判别模型的分类器吧
